In [9]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print (device)
import time 
import numpy as np
import torch.nn as nn
from torch.nn import functional as F

cuda


In [2]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)

np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)
np_rand1 = np_rand1.cpu().numpy()
np_rand2 = np_rand2.cpu().numpy()
start_time =time.time()

rand =(torch_rand1 @ torch_rand2)

end_time = time.time()
elapsed_time= end_time-start_time
print("GPU:")
print(f"{elapsed_time:8f}")

start_time =time.time()

rand = np.multiply(np_rand1,np_rand2)

end_time = time.time()
elapsed_time= end_time-start_time
print("CPU:")
print(f"{elapsed_time:8f}")


GPU:
0.074204
CPU:
0.102480


In [3]:
#10% -> 0.1 90% ->0.9 (probability to appear in a tensor)
#Draws 5 examples of that distrubition
probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities,num_samples=10,replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [4]:
tensor= torch.tensor([1,2,3,4,5])
out = torch.cat((tensor,torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5, 5])

In [5]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [6]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [7]:
torch.exp(out)


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [8]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [9]:
tensor1= torch.tensor([1,2,3])
tensor2= torch.tensor([31,52,35])
tensor3= torch.tensor([12,24,43])

stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[ 1,  2,  3],
        [31, 52, 35],
        [12, 24, 43]])

In [10]:
#producto punto 
#n dot function

import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=True)
print(linear(sample))

tensor([-7.7787,  1.7936, -0.5573], grad_fn=<ViewBackward0>)


In [11]:
import torch.nn.functional as F

#Create a tensor 
tensor1 = torch.tensor([1.0,2.0,3.0])
#Apply softmax using torc.nn functional.sosftmax()
softmax_output = F.softmax(tensor1,dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [12]:

# Define an embedding layer:
# 1000 = total vocabulary/items (num_embeddings)
# 64   = vector dimension size (embedding_dim)
embedding = torch.nn.Embedding(num_embeddings=100, embedding_dim=64)

# Pass discrete integer IDs (e.g., token IDs 3, 42, 99)
input_ids = torch.tensor([3, 42, 99])
embedded_output = embedding(input_ids)

print(embedded_output.shape)
# Output: torch.Size([3, 64]) -> 3 items, each represented by a 64-dim vector

torch.Size([3, 64])


In [13]:
a= torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

c = a@b
print(torch.matmul(a,b))
print (c)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [6]:
#carefull be aware of data compatility and types
int_64 = torch.randint(1,(3,2)).float()
float_32 = torch.rand(2,3)

result = int_64 @ float_32
print(result)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
a = torch.rand(2,3,5)
print(a.shape)

x,y,z= a.shape
print(x,y,z)

a = a.view(x,y,z)
print(a.shape)

print(a)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])
tensor([[[0.2002, 0.7603, 0.2155, 0.2169, 0.3042],
         [0.4050, 0.4135, 0.8043, 0.0047, 0.0270],
         [0.5197, 0.1308, 0.1213, 0.2254, 0.8532]],

        [[0.2077, 0.4158, 0.2145, 0.1758, 0.3377],
         [0.9244, 0.4886, 0.8320, 0.7711, 0.7427],
         [0.6463, 0.5732, 0.9702, 0.0157, 0.0232]]])


In [14]:
x = torch.tensor([10],dtype = torch.float32)
#y = nn.ReLU(x)
#y = F.sigmoid(x)
y = F.tanh(x)
print(y)

tensor([1.])
